"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#6272a4)\
[  ](bg:#6272a4 fg:#282a36)\
[](bg:#bd93f9 fg:#6272a4)\
$directory\
[](fg:#bd93f9 bg:#44475a)\
$git_branch\
$git_state\
$git_status\
$git_metrics\
[](fg:#44475a bg:#282a36)\
[ ](fg:#282a36)\
\n$sudo\
$character"""

right_format = """
(fg:#44475a bg:#44475a)\
$aws\
$kubernetes\
$container\
$ruby\
$nodejs\
$elixir\
$stern\
$time\
$cmd_duration
"""
[directory]
style = "fg:#f8f8f2 bg:#bd93f9"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#44475a"
format = '[[ $symbol $branch ](fg:#bd93f9 bg:#44475a)]($style)'

[git_status]
style = "bg:#44475a"
format = '[[($all_status$ahead_behind )](fg:#bd93f9 bg:#44475a)]($style)'

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:#bd93f9 bg:#44475a"
deleted_style = "fg:#ff5555 bg:#44475a"
disabled = false

[git_state]
disabled = false

[time]
disabled = false
time_format = "%R"                                      # Hour:Minute Format
style = "bg:#282a36"
format = '[[  $time ](fg:#6272a4 bg:#282a36)]($style)'

[cmd_duration]
format = "[  $duration ]($style)"
style = "fg:#f8f8f2 bg:#44475a"
disabled = false

[aws]
symbol = "  "
disabled = false

[buf]
symbol = " "

[c]
symbol = " "

[cmake]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_commit]
tag_symbol = '  '

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[kubernetes]
disabled = false

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "
